-- =============================================================
-- GT Anywhere · 2e Pathway — 01-schema.sql
-- Run this FIRST in the Supabase SQL editor, then 02-security.sql.
-- Safe to re-run: everything is IF NOT EXISTS / OR REPLACE.
-- =============================================================

-- ---------- case reference numbers (2E-0001, 2E-0002, ...) ----------

create sequence if not exists public.case_ref_seq start with 1;

create or replace function public.next_case_ref()
returns text
language sql
volatile
as $$
  select '2E-' || lpad(nextval('public.case_ref_seq')::text, 4, '0');
$$;

-- ---------- cases ----------

create table if not exists public.cases (
  id                    uuid primary key default gen_random_uuid(),
  ref                   text unique not null default public.next_case_ref(),
  created_at            timestamptz not null default now(),
  created_by            uuid default auth.uid(),

  -- Step 01 · student & who is raising this
  student_name          text not null,
  grade_band            text not null,
  observed_on           date not null,
  raised_by             text not null,
  raised_by_role        text,
  assigned_aa           text,

  -- Step 02 · what are you seeing
  domains               text[] not null default '{}',
  observation           text not null,
  objective_data        text,
  strength              text not null,

  -- Step 03 · rule out the ordinary explanation
  ruleouts              text[] not null default '{}',
  home_context          text,

  -- Step 04 · documentation status
  doc_status            text not null,
  known_accommodations  text,
  prior_setting         text,

  -- Step 05 · what has been tried
  tried                 text[] not null default '{}',
  tried_note            text,
  advisor_read          text,

  -- pathway position
  stage                 text not null default 'signal'
    check (stage in ('signal','documented','family','plan','review','fit'))
);

create index if not exists cases_stage_idx      on public.cases (stage);
create index if not exists cases_created_at_idx on public.cases (created_at);

-- ---------- case_steps · generated by buildPlan() at intake ----------

create table if not exists public.case_steps (
  id           uuid primary key default gen_random_uuid(),
  case_id      uuid not null references public.cases (id) on delete cascade,
  created_at   timestamptz not null default now(),
  title        text not null,
  rationale    text,
  owner_label  text,
  due_on       date,
  severity     text not null default 'normal'
    check (severity in ('gate','urgent','normal'))
);

create index if not exists case_steps_case_id_idx on public.case_steps (case_id, created_at);

-- ---------- case_notes · append-only dated log ----------

create table if not exists public.case_notes (
  id           uuid primary key default gen_random_uuid(),
  case_id      uuid not null references public.cases (id) on delete cascade,
  created_at   timestamptz not null default now(),
  created_by   uuid default auth.uid(),
  author_name  text,
  body         text not null
);

create index if not exists case_notes_case_id_idx on public.case_notes (case_id, created_at desc);

-- ---------- stage_transitions · append-only audit of stage moves ----------

create table if not exists public.stage_transitions (
  id           uuid primary key default gen_random_uuid(),
  case_id      uuid not null references public.cases (id) on delete cascade,
  created_at   timestamptz not null default now(),
  created_by   uuid default auth.uid(),
  from_stage   text,
  to_stage     text not null,
  actor_name   text
);

create index if not exists stage_transitions_case_id_idx on public.stage_transitions (case_id, created_at);
